=== Zkir/generalized_landcovers/taginfo-project-schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Taginfo",
  "definitions": {
    "Taginfo": {
      "title": "Taginfo",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "data_format": {
          "type": "integer",
          "description": "data format version, currently always 1, will get updated if there are incompatible changes to the format"
        },
        "data_url": {
          "type": "string",
          "format": "uri",
          "description": "the URL under which this project file can be accessed"
        },
        "data_updated": {
          "type": "string",
          "pattern": "20\\d{2}\\d{2}\\d{2}T\\d{2}\\d{2}\\d{2}Z",
          "description": "yyyymmddThhmmssZ timestamp when project file was updated"
        },
        "project": {
          "$ref": "#/definitions/Project"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tag"
          }
        }
      },
      "required": ["data_format", "project", "tags"]
    },
    "Project": {
      "title": "Project",
      "type": "object",
      "description": "meta information about the project",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "name of the project"
        },
        "description": {
          "type": "string",
          "description": "short description of the project"
        },
        "project_url": {
          "type": "string",
          "format": "uri",
          "description": "homepage of the project with general information"
        },
        "doc_url": {
          "type": "string",
          "format": "uri",
          "description": "documentation of the project and especially the tags used"
        },
        "icon_url": {
          "type": "string",
          "format": "uri",
          "description": "project logo, should work in 16x16 pixels on white and light gray backgrounds"
        },
        "contact_name": {
          "type": "string",
          "description": "contact name (needed for taginfo maintainer)"
        },
        "contact_email": {
          "type": "string",
          "format": "email",
          "description": "contact email (needed for taginfo maintainer)"
        }
      },
      "required": [
        "name",
        "description",
        "project_url",
        "contact_name",
        "contact_email"
      ]
    },
    "Tag": {
      "title": "Tag",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "key": {
          "type": "string",
          "description": "OSM tag key"
        },
        "value": {
          "type": "string",
          "description": "OSM tag value (if not supplied it means 'all values')"
        },
        "object_types": {
          "type": "array",
          "description": "OSM object types this key/tag can be used for",
          "items": {
            "$ref": "#/definitions/ObjectType"
          }
        },
        "description": {
          "type": "string",
          "description": "how the key/tag is used in this project"
        },
        "doc_url": {
          "type": "string",
          "format": "uri",
          "description": "link to further documentation of the project about this specific key/tag"
        },
        "icon_url": {
          "type": "string",
          "format": "uri",
          "description": "URL of an icon, should work in 16x16 pixels on white and light gray backgrounds"
        }
      },
      "required": ["key"]
    },
    "ObjectType": {
      "title": "ObjectType",
      "type": "string",
      "enum": ["node", "way", "relation", "area"]
    }
  }
}

=== Zkir/generalized_landcovers/taginfo.json
{
    "data_format": 1,
    "data_updated": "20251031T132908Z",
    "project": {
        "contact_email": "zkir@zkir.ru",
        "contact_name": "Kirill B. aka Zkir",
        "description": "OSM-based map of Earth land covers",
        "name": "OpenLandcoverMap ;)",
        "project_url": "https://github.com/Zkir/generalized_landcovers"
    },
    "tags": [
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "allotments"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "arctic_desert"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "bare_earth"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "bare_rock"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "beach"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "blockfield"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "cemetery"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "desert"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "drainage_basin"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "farmland"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "farmyard"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "glacier"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "government"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "grassland"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "greenhouse_horticulture"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "heath"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "inundation_area"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "irrigation_district"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "landfill"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "logging"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "logistics"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "meadow"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "mine"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "moor"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "mud"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "oil_field"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "oilfield"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "orchard"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "paddy"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "peat_cutting"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "plant_nursery"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "playa"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "quarry"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "railway"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "rangeland"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "rocket_range"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "salt_pond"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "sand"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "scree"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "scrub"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "sediment"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "shingle"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
            "value": "spoils"
        },
        {
            "description": "Accepted as landcover, but not rendered.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "till"
        },
        {
            "description": "Rendered as landcover.",
            "key": "natural",
            "object_types": [
                "area"
            ],
            "value": "tundra"
        },
        {
            "description": "Rendered as landcover.",
            "key": "landuse",
            "object_types": [
                "area"
            ],
